version: '3.7'
services:
  redact:
    image: '${REDACT_IMAGE}'
    container_name: ${REDACT_CONTAINER_NAME}
    depends_on:
      redact-gpu:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-o",
          "/dev/null",
          "-I",
          "-w",
          "\"%{http_code}\"",
          "http://127.0.0.1:8787"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: "10s"
    restart: always
    ports:
      - '${REDACT_API_PORT}:8787'
    volumes:
      - ${INSTALLATION_DIR}/${REDACT_LICENSE_FILE}:/license.bal
    environment:
      REDACT_INFER_METRICS_URL: 'redact-gpu:8000'
      REDACT_GPU_URL: 'redact-gpu:8001'
      DISABLE_FACES: ${DISABLE_FACES}
      DISABLE_LICENSE_PLATES: ${DISABLE_LICENSE_PLATES}
      DISABLE_BLUR: ${DISABLE_BLUR}
      DISABLE_EXTRACT: ${DISABLE_EXTRACT}
      DISABLE_DNAT: ${DISABLE_DNAT}

  redact-gpu:
    image: ${REDACT_GPU_IMAGE}
    container_name: ${REDACT_GPU_CONTAINER_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "httpd=`curl -sL --connect-timeout 3 -w \"%{http_code}\\

            \" \"http://127.0.0.1:8000/v2/health/ready\" -o /dev/null` || echo \"000\"; if [[ \"$$httpd\" != \"200\" ]]; then exit 1; fi; exit 0"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: "900s"
    restart: always
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: ${GPU_IDS}

  redact-utils:
    image: ${REDACT_UTILS_IMAGE}
    container_name: ${REDACT_UTILS_CONTAINER_NAME}
    depends_on:
      redact:
        condition: service_healthy
    ports:
      - '${REDACT_UI_PORT}:80'
    environment:
      REDACT_URL: http://${HOST_IP}:${REDACT_API_PORT}
